"""Add favorite_stocks table

Revision ID: 28716b577075
Revises: 07089d132c5c
Create Date: 2026-03-27 10:12:32.401322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28716b577075'
down_revision: Union[str, None] = '07089d132c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_stocks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('symbol', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_stocks_user_id'), 'favorite_stocks', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorite_stocks_symbol'), 'favorite_stocks', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_stocks_symbol'), table_name='favorite_stocks')
    op.drop_index(op.f('ix_favorite_stocks_user_id'), table_name='favorite_stocks')
    op.drop_table('favorite_stocks')
    # ### end Alembic commands ###
