"""Add strategy_id to signal_stocks table

Revision ID: a1b2c3d4e5f6
Revises: 5d58b091f11c
Create Date: 2026-04-30 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '5d58b091f11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add strategy_id column to signal_stocks table
    op.add_column('signal_stocks', 
        sa.Column('strategy_id', sa.UUID(), nullable=True)
    )
    
    # Create index for strategy_id for efficient queries
    op.create_index(
        op.f('ix_signal_stocks_strategy_id'), 
        'signal_stocks', 
        ['strategy_id'], 
        unique=False
    )
    
    # Create foreign key constraint (optional - if we want strict referential integrity)
    op.create_foreign_key(
        'fk_signal_stocks_strategy_id',
        'signal_stocks',
        'strategies',
        ['strategy_id'],
        ['id'],
        ondelete='SET NULL'
    )
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key first if it was created
    # op.drop_constraint('fk_signal_stocks_strategy_id', 'signal_stocks', type_='foreignkey')
    
    # Drop index
    op.drop_index(op.f('ix_signal_stocks_strategy_id'), table_name='signal_stocks')
    
    # Drop column
    op.drop_column('signal_stocks', 'strategy_id')
    # ### end Alembic commands ###
