"""Add default strategy seed

Revision ID: add_default_strategy_seed
Revises: 16e47539e731
Create Date: 2026-05-06 19:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_default_strategy_seed'
down_revision: Union[str, None] = '16e47539e731'
branch_labels: Union[str, Sequence[str]] = None
depends_on: Union[str, Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Insert default strategy
    from app.infrastructure.database.default_strategy_seed import get_default_strategy_entity
    from app.domain.entities.strategy import Strategy
    
    default_strategy = get_default_strategy_entity()
    
    op.bulk_insert_mappings(
        Strategy,
        [
            {
                'id': default_strategy.id,
                'user_id': default_strategy.user_id,
                'name': default_strategy.name,
                'description': default_strategy.description,
                'is_active': default_strategy.is_active,
                'dsl_definition': default_strategy.dsl_definition,
                'dsl_hash': default_strategy.dsl_hash,
                'version': default_strategy.version,
                'created_at': sa.func.now(),
                'updated_at': sa.func.now()
            }
        ]
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM strategies WHERE id = '00000000-0000-0000-0000-000000000001'");
    # ### end Alembic commands ###
