"""Add default strategy seed

Revision ID: add_default_strategy_seed
Revises: 16e47539e731
Create Date: 2026-05-06 19:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_default_strategy_seed'
down_revision: Union[str, None] = '16e47539e731'
branch_labels: Union[str, Sequence[str]] = None
depends_on: Union[str, Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Insert default strategy
    from app.infrastructure.database.default_strategy_seed import get_default_strategy_entity
    
    default_strategy = get_default_strategy_entity()
    
    op.execute(
        "INSERT INTO strategies (id, user_id, name, description, is_active, dsl_definition, dsl_hash, version, created_at, updated_at) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
        "ON CONFLICT (id) DO NOTHING",
        (
            str(default_strategy.id),
            str(default_strategy.user_id),
            default_strategy.name,
            default_strategy.description,
            default_strategy.is_active,
            default_strategy.dsl_definition,
            default_strategy.dsl_hash,
            default_strategy.version,
            sa.func.now(),
            sa.func.now()
        )
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM strategies WHERE id = '00000000-0000-0000-0000-000000000001'");
    # ### end Alembic commands ###
