"""Add execution_plans table

Revision ID: b2c3d4e5f6g7
Revises: 16e47539e731
Create Date: 2026-05-06 10:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6g7'
down_revision: Union[str, None] = '16e47539e731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_plans',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('strategy_id', sa.UUID(), nullable=False),
        sa.Column('stocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
        sa.Column('timeframe', sa.String(length=20), nullable=False, server_default='day'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_plans_user_id'), 'execution_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_execution_plans_strategy_id'), 'execution_plans', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_execution_plans_is_active'), 'execution_plans', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_plans_is_active'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_strategy_id'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_user_id'), table_name='execution_plans')
    op.drop_table('execution_plans')
    # ### end Alembic commands ###
